### ISSUE TITLE
No POST anymore with pyramid_whoauth

### ISSUE THREAD

**Issue by patrickbr** [mozilla-services/pyramid_whoauth#2]
Hi,

we are using repoze.who via pyramid_who in a Pyramid application for SSO via pysaml2. However, as soon the authentication policy is enabled, our application is not able to process POSTed data anymore.

For example, a POST of size 3808 bytes failes with

DisconnectionError: The client disconnected while sending the POST/PUT body (3808 more bytes were expected)

This behaviour only occurs if self._getAPI is called in WhoAuthenticationPolicy. As soon as the method is commented out, POST requests start to work correctly again.

We are serving the application via pserve.

Any help is highly appreciated!

**Comment by rfk** [comment]
Are you using the most recent version of the code?  I can't find `self._getAPI` anywhere in the codebase.

**Comment by rfk** [comment]
Ah, I wonder if you are actually using https://github.com/Pylons/pyramid_who, which is a different project with similar goals, and which does have such a `_getAPI` method.

**Comment by patrickbr** [comment]
Yes, I am very sorry. We are currently using pyramid_who. However, I just figured out what the problem was: the pysaml2 plugin is not reading the content of the POST request correctly during identification, leading to an empty environ['wsgi.input'] which was later restored using an empty string. Subsequent reads of the POST content then found the old CONTENT_LENGTH, but an empty POST request. So, no problem in repoze.who :)
